### Numpy Intro Notebook

In [3]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])

In [4]:
a[0] = 10

In [7]:
b = a*np.array([2,0,2,0])

In [11]:
print(a.shape)
print(a.dtype)
print(a.data)
print(a.size)
print(a.itemsize)
print(a.ndim)

(4,)
int64
4
8
1


In [17]:
l = [1,2,3,4]
a = np.array(l)

In [18]:
# l.append(5)
l += [5]
l

[1, 2, 3, 4, 5]

In [19]:
a += np.array([5])
a

array([6, 7, 8, 9])

In [20]:
l = l*2
l

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [21]:
a = a*2
a

array([12, 14, 16, 18])

Operations in numpy works on element level!!!

In [23]:
l1 = [1,2,3]
l2 = [4,5,6]
a1 = np.array(l1)
a2 = np.array(l2)

### Dot Product

In [24]:
# In Python
dot = 0
for i in range(len(l1)):
    dot += l1[i]*l2[i]

dot



32

In [25]:
# In Numpy
dot = np.dot(a1,a2)
dot

32

In [26]:
# Second way
sum = a1*a2
dot = np.sum(sum)
dot

32

### Testing Speed Lists vs Numpy Arrays

In [10]:
import timeit
a = np.random.randn(1000)
b = np.random.randn(1000)

A = list(a)
B = list(b)

T = 1000

def list_dot():
    dot = 0
    for i in range(len(A)):
        dot += A[i]*B[i]
    return dot

def array_dot():
    return np.dot(a,b)

In [11]:
# Lists
timer = timeit.Timer(list_dot)
iterations = 1000
repetitions = 5

execution_time = timer.timeit(number=iterations)
print(f"Execution time: {execution_time:.6f} seconds")

Execution time: 0.099408 seconds


In [12]:
# Arrays
timer = timeit.Timer(array_dot)
iterations = 1000
repetitions = 5

execution_time = timer.timeit(number=iterations)
print(f"Execution time: {execution_time:.6f} seconds")

Execution time: 0.002868 seconds


### Multi-dimension arrays - nd arrays

In [18]:
# Indexing
a = np.array([[1,2], [3,4]])
print(a)

print(a[1,1])
print(a[-1,-1])

[[1 2]
 [3 4]]
4
4


In [17]:
# Slicing
a = np.array([[1,2,3],[4,5,6]])
print(a)

print(a[0,:])
print(a[:,0])
print(a[0:1,:])
print(a[0:2, 1])
print(a)

[[1 2 3]
 [4 5 6]]
[1 2 3]
[1 4]
[[1 2 3]]
[2 5]


In [24]:
# Boolean Index
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print()

bool_idx = a > 2

print(bool_idx)
print(a[bool_idx])
print(a[a > 2])

print()

b = np.where(a>2, a, -1)
print(b)

[[1 2]
 [3 4]
 [5 6]]

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]

[[-1 -1]
 [ 3  4]
 [ 5  6]]


In [27]:
# Fancy Indexing
a = np.array([10,14,54,63,64,12,46])
print(a)
print()

b = [1,3,6]

print(a[b])

indices = np.argwhere(a%2==0)
print(indices)
indices = indices.flatten()

print(a[indices])

[10 14 54 63 64 12 46]

[14 63 46]
[[0]
 [1]
 [2]
 [4]
 [5]
 [6]]
[10 14 54 64 12 46]


### Reshaping

In [34]:
# Reshape
a = np.arange(1,9)
print(a)
print(a.shape)

b = a.reshape((2,4))
print(b.shape)
print(b)
print()
b = a.reshape((4,2))
print(b)

[1 2 3 4 5 6 7 8]
(8,)
(2, 4)
[[1 2 3 4]
 [5 6 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [35]:
# New Axis
a = np.arange(1,7)
print(a)

b = a[np.newaxis,:]
print(b)
print()
b = a[:,np.newaxis]
print(b)

[1 2 3 4 5 6]
[[1 2 3 4 5 6]]

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


### Concatenation

In [37]:
a = np.array([[1,2],[3,4]])
print(a)
b = np.array([[5,6]])

c = np.concatenate((a,b),axis=0)
print(c)
c = np.concatenate((a,b),axis=None)
print(c)
c = np.concatenate((a,b.T),axis=1)
print(c)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[[1 2 5]
 [3 4 6]]


In [38]:
# hstack and vstack
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

c = np.hstack((a,b))
print(c)

c = np.vstack((a,b))
print(c)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


### Broadcasting